### ISSUE TITLE
error when closing plate viewer view

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/HCS-Tools#2] opened 2013-02-13 08:43 UTC
the error message is the following:
ERROR    HeatMapViewerNodeView   NodeView.onClose() causes an error during closing node view, reason: null

**Comment by fmeyenhofer** [comment] 2013-03-06 18:51
I can't reproduce this error.

**Comment by stoeter** [comment] 2013-04-15 09:35
I get the same error message on closing the plate viewer

**Closed as completed** 2013-04-20 10:23 UTC
