### ISSUE TITLE
custom color map of plate viewer

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#15] opened 2013-04-15 13:54 UTC
The color map "custom" does work properly in my hands. Issues:
1) color map selection window doesnt open if reference control was selected with many data points (e.g. library)
2) colors rectangle doesnt fit to indicated mean (and +-3SD) calculation
3) color map is wrong, I tried red-white-blue, the color bar shows red-white-blue but I see wells labelled with purple
4) custom color doesn't accept chosen color (in most times, only right click on thumbs works)
5) custom color map is "forgotten" when selecting other color map, or when node is reseted and reselected
6) custom should be saved or color map should be easily "generated" by user (see also next point)
7) it would be nice to have default color maps editable in KNIME preferences (as .txt?, like a look up table for images (LUT))
- in general it would be nice to use population statistics to generate the color scale (e.g. from boxplot statistics)
  ![Screen shot 2013-04-15 at 3 41 01 PM](https://f.cloud.github.com/assets/878953/380894/f617c09c-a5d3-11e2-8018-b4928c307aa6.png)
  ![Screen shot 2013-04-15 at 3 45 05 PM](https://f.cloud.github.com/assets/878953/380895/f8504348-a5d3-11e2-8471-4788e68161b6.png)

**Comment by stoeter** [comment] 2013-04-15 14:31
- double-click on color scale @ bottom opens color map dialog (nice to have)

**Comment by fmeyenhofer** [comment] 2013-04-20 11:08
Point 1 is not clear to me, or in other words I was not able to reproduce the error so far.
I think the point 2, concerning the wrong calculation of the mean and SD, was addressed in the commit b05ef46fbded202fb3618ed98ce06709f03f34de. 
Point 3 seems to be a problem of the color space interpolation I will have to look into it.
Point 4, or similar was discussed in issue #7, maybe we'll have to re-open that issue.

Points 5-7 were taken out to create issue #18, a feature request.

**Comment by fmeyenhofer** [comment] 2013-09-21 14:40
The color interpolation works correctly now

**Closed as completed by fmeyenhofer** 2013-09-21 14:40 UTC
Labels: bugs
