### ISSUE TITLE
Join well position

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#21] opened 2013-12-06 11:58 UTC
feature request - new node:
- reverse operation of expand well position node
- join plateRow and plateColumn (columns selectable) into column plateWell (2,3 -> B3)
- default option keep source columns
- option to generate well position with standard length (B03)

**Comment by niederle** [comment] 2015-09-29 08:31
duplicate of #83

**Closed as completed by niederle** 2015-09-29 08:31 UTC
Labels: feature request
